[package]
name = "sht20"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-modbus = "0.9"
tokio-serial = "5.4"
